### ISSUE TITLE
Project plan: Goal section

### ISSUE THREAD

**Issue by cecilianor** [cecilianor/Qt-thesis#12]
The goals section in the project plan has been written by Nils  is ready for review. Cecilia will do this, make any final updates and close the issue.

Tasks:
- [x] Write the first draft of the Goals section.
- [x] Review Goals section.
- [x] Make any final updates.

New tasks based on feedback from Xiang:
- [ ] Tie goals as much as possible to functionality or something that's more concrete or specific.

**Comment by cecilianor** [comment]
I think this section looks alright. Maybe we could have a bit more in the result goals section, but I can't come up with anything else. I'm closing the issue now, but feel free to re-open it if we need to add more later.

**Comment by cecilianor** [comment]
Issue reopoened after getting feedback from Xiang. Try to tie all goals to something that's more concrete, specific, or functional.
