### ISSUE TITLE
Project plan: Problem domain, Restrictions, and Delimitation

### ISSUE THREAD

**Issue by cecilianor** [cecilianor/Qt-thesis#13]
The following topics must be written about in the project plan. Update it to 'Ready-for-review' (if you'd like a team mate to review it) or close the issue once completed. This updates #3 once completed.

Tasks:
- [x] Write about problem domain.
- [x] Write about restrictions.
- [x] Write about delimitation.
- [x] Review the sections.
