### ISSUE TITLE
Project plan: Restructuring Quality Assurance section

### ISSUE THREAD

**Issue by cecilianor** [cecilianor/Qt-thesis#14]
Estimated work time: 8 hours

This section must be rewritten and restructured to fit the content. The way the project plan is right now, some sections repeat themselves and may not be organized in the best way.

Tasks:
- [x] Remove "double" sections that repeat the same content twice.
- [x] Determine if Git, usage of coding standards, or other topics that improve quality, belong in the QA section or their own sections.
- [x] Proofread these parts of the report.
- [x] Review.

**Comment by cecilianor** [comment]
This is now complete. I think the structure in QA looks alright now, so I'm closing the issue. We could probably still proofread and cut some of the content, but I'd say the restructuring is completed now.
