### ISSUE TITLE
Create, Write, Complete, and Deliver Project Plan

### ISSUE THREAD

**Issue by cecilianor** [cecilianor/Qt-thesis#3]
# Tasks
- [x] Create Overleaf file for the project plan.
- [x] Add inn all relevant sections. Include sources here to make it easier to include them in the final report in a few months.

# Project Plan Sections
- [ ] Goals and Restrictions
  - [ ] Background
  - [x] Project goals (with effect goals, result goals, and learning goals)
  - [ ] Restrictions

- [ ] Scope
  - [ ] Problem Area
  - [ ] Problem Delimitation
  - [ ] Problem Description

- [x] Project Organisation
  - [x] Responsibilities and roles
  - [x]  Routines and group rules (with group contract, can be an appendix)

- [ ] Planning, Follow-Up, and Reporting of the Project
  - [x] Overview of project:
    - Choice of project development model/ process framework with argumentation/reasoning where choices are justified/explained.
    -  Description of the group's way of following the model.
  - [x] Plan for status meetings and points in time where decisions must be made during the development process (aka deadlines).

- [ ] Organization of Quality Assurance
  - [x] Documentation, standards, configuration controls, tools
  - [x] Plan for inspections and testing
  - [ ] Risk analysisk: Identified risks, analysis of risks, proposed solutions/measures/countermeasures, follow-up of technological, business, and project group risks

- [x] Plan for Execution
  - [x] Gantt chart with acitivites, milestones and deadlines for when decisions must be made.
  - Note: These activities must be project specific. Make them specific (vague: "write report", specific: "complete final version of the first report draft").

Separate issues may be created later if we split tasks among team members if we think it's useful.
